# Generated by Django 5.2.7 on 2025-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favoris_par', to='products.produit'),
        ),
    ]
