# Generated by Django 5.2.7 on 2025-10-29 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_client_favoris'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='accounts.client', verbose_name='Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_publication'],
                'unique_together': {('client', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='ReponseAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Réponse')),
                ('date_reponse', models.DateTimeField(auto_now_add=True, verbose_name='Date de réponse')),
                ('avis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reponse', to='reviews.avis', verbose_name='Avis')),
            ],
            options={
                'verbose_name': 'Réponse à un avis',
                'verbose_name_plural': 'Réponses aux avis',
            },
        ),
    ]
