# Generated by Django 5.2.7 on 2025-10-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_client_favoris'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('montant_produits', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant produits')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('telephone_livraison', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('mode_paiement', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('wave', 'Wave'), ('carte_bancaire', 'Carte Bancaire'), ('a_la_livraison', 'Paiement à la livraison')], max_length=20, verbose_name='Mode de paiement')),
                ('paiement_valide', models.BooleanField(default=False, verbose_name='Paiement validé')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='accounts.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('taille', models.CharField(blank=True, max_length=10, verbose_name='Taille')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
