# Generated by Django 5.2.7 on 2025-10-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('couleur', models.CharField(default='#007bff', help_text='Code hexadécimal', max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('tailles_disponibles', models.JSONField(blank=True, default=list, help_text='Liste des tailles', verbose_name='Tailles disponibles')),
                ('image_principale', models.ImageField(upload_to='produits/', verbose_name='Image principale')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de modération'), ('publie', 'Publié'), ('refuse', 'Refusé'), ('archive', 'Archivé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('visibilite', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='products.categorie', verbose_name='Catégorie')),
                ('etiquettes', models.ManyToManyField(blank=True, related_name='produits', to='products.etiquette', verbose_name='Étiquettes')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='accounts.vendeur', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/galerie/', verbose_name='Image')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image de produit',
                'verbose_name_plural': 'Images de produit',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['slug'], name='products_pr_slug_376561_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie', 'statut'], name='products_pr_categor_d4e54f_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['-date_ajout'], name='products_pr_date_aj_e76849_idx'),
        ),
    ]
